### PR TITLE
fix: react 19 types

### LINKED ISSUE #98: Adapt intrinsic-jsx for React 19
CC @Abse2001 

/bounty $10

### PR DESCRIPTION
**Pull request by Abse2001**
/claim #98
/closes #98

### CODE REVIEW

File: lib/intrinsic-jsx.d.ts [hunk 1]
```diff
@@ -2,44 +2,51 @@ import type * as FN from "./jscad-fns"
 
 type CommonProps = { key?: any }
 
-declare global {
+export interface TscircuitJscadElements {
```
Comment (seveibar) [inline lib/intrinsic-jsx.d.ts:5]:
```suggestion
export interfaceJscadElements {
```

**Review by seveibar — COMMENTED** [review]
Can you update the @types/react to confirm react 19 types work

**Comment by Abse2001** [comment]
image

**Review by seveibar — APPROVED** [review]
